name: build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.14.0
        include:
          - os: ubuntu-latest
            ocaml-version: 4.08.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-ocaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: setup
        run: |
          opam pin add . -y --no-action
          opam depext -y toml
          opam install -y ./*.opam --deps-only --with-test
          opam upgrade --fixup
      - name: build
        run: opam exec -- dune build @install
      - name: test
        run: opam exec -- dune runtest
