name: Main Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - !{ci-systems}
        ocaml-compiler:
          - !{edition}
        skip_test:
          - false
![if:min-edition]
        include:
          - os: !{ci-first-system}
            ocaml-compiler: !{min-edition}
            skip_test: true
![fi]

    runs-on: ${{ matrix.os }}
!(github-worlflow-env)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v2-${{ runner.os }}-!{name}-${{ matrix.ocaml-compiler }}-${{ hashFiles('opam/*.opam') }}
#          restore-keys: |
#            v2-${{ runner.os }}-opam-${{ matrix.ocaml-compiler }}-

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-pin: false
          opam-depext: false

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com
![if:field:opam-repo]
      - run: |
         opam repo add extra !(opam-repo)
         sudo apt-get update

![else]
      # define opam-repo = "git+https://" to add an extra opam repo
![fi]
      - run: opam pin add . -y --no-action

      - run: opam depext -y !{packages}
#        if: steps.cache-opam.outputs.cache-hit != 'true'

      - run: opam install -y opam/*.opam --deps-only --with-test
#        if: steps.cache-opam.outputs.cache-hit != 'true'

#      - run: opam upgrade --fixup
#        if: steps.cache-opam.outputs.cache-hit == 'true'

      - run: dos2unix scripts/*.sh
        if: matrix.os == 'windows-latest'
!(github-workflow-before-build)
      - run: make build
!(github-workflow-after-build)
      - name: run test suite
        run: |
          ./scripts/before.sh test
          opam exec -- dune build @runtest
          ./scripts/after.sh test
        if: matrix.skip_test  != 'true'

      - name: test source is well formatted
        run: make fmt
        continue-on-error: true
        if: matrix.ocaml-compiler == '!{edition}' && matrix.os == '!{ci-first-system}'

      - name: build-doc
        if: github.ref == 'refs/heads/master' && matrix.ocaml-compiler == '!{edition}' && matrix.os == '!{ci-first-system}'
        run: |
             sudo apt install -yqq python3-sphinx python3-sphinx-rtd-theme
             opam install -y dune odoc
             make doc
             touch _drom/docs/.nojekyll
             touch _drom/docs/!{sphinx-target}/.nojekyll
             touch _drom/docs/!{odoc-target}/.nojekyll

      - name: deploy-doc
        uses: JamesIves/github-pages-deploy-action@3.6.2
        if: github.ref == 'refs/heads/master' && matrix.ocaml-compiler == '!{edition}' && matrix.os == '!{ci-first-system}'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _drom/docs/
          CLEAN: true
